# Generated by Django 2.1.5 on 2021-05-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional attributes')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_group', models.BooleanField(default=False)),
                ('colossal', models.BooleanField(default=False)),
                ('beard', models.BooleanField(default=False)),
                ('buste', models.BooleanField(default=False)),
                ('cuirassed_buste', models.BooleanField(default=False)),
                ('capite_velato', models.BooleanField(default=False)),
                ('headgear', models.BooleanField(default=False)),
                ('corona_laurea', models.BooleanField(default=False)),
                ('corona_civica', models.BooleanField(default=False)),
                ('corona_radiata', models.BooleanField(default=False)),
                ('other_wreath_crown', models.BooleanField(default=False)),
                ('statue', models.BooleanField(default=False)),
                ('toga', models.BooleanField(default=False)),
                ('equestrian', models.BooleanField(default=False)),
                ('cuirass', models.BooleanField(default=False)),
                ('heroic_semi_nude', models.BooleanField(default=False)),
                ('seated', models.BooleanField(default=False)),
                ('recurved', models.BooleanField(default=False)),
                ('terminus_ante_quem', models.BooleanField(default=False)),
                ('terminus_post_quem', models.BooleanField(default=False)),
                ('part_statue_group', models.BooleanField(default=False)),
                ('relief', models.BooleanField(default=False)),
                ('contabulata', models.BooleanField(default=False)),
                ('sword_belt', models.BooleanField(default=False)),
                ('paludamentum', models.BooleanField(default=False)),
                ('miniature', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Context')),
            ],
        ),
        migrations.CreateModel(
            name='Emperor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name group')),
                ('reference', models.TextField(blank=True, null=True, verbose_name='Reference statue group')),
            ],
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment_height')),
            ],
        ),
        migrations.CreateModel(
            name='Iconography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Iconography cuirass')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place name')),
                ('long_coord', models.FloatField(blank=True, null=True, verbose_name='Longitude coordinate')),
                ('lat_coord', models.FloatField(blank=True, null=True, verbose_name='Lattitude coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='LocationProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_province', to='ripdapp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Filename')),
                ('hyperlink', models.CharField(blank=True, max_length=255, null=True, verbose_name='Filename')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order of photos')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_grapher', to='ripdapp.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name photographer')),
            ],
        ),
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('reference', models.TextField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('startdate', models.IntegerField(null=True, verbose_name='Start date')),
                ('enddate', models.IntegerField(null=True, verbose_name='End date')),
                ('arachne', models.IntegerField(blank=True, null=True, verbose_name='Arachne number')),
                ('lsa', models.IntegerField(blank=True, null=True, verbose_name='LSA number')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_alternativ', to='ripdapp.Alternative')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_alternative', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_attributes', to='ripdapp.Attributes')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_attributes', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_context', to='ripdapp.Context')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_context', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitEmperor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emperor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_emperor', to='ripdapp.Emperor')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_emperor', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitIconcuirass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_cuirass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_iconcuirass', to='ripdapp.Iconography')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_iconcuirass', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_location', to='ripdapp.Location')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_location', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_material', to='ripdapp.Material')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_material', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order of the photo’s')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_photo', to='ripdapp.Photo')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_photo', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitRecarved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_recarved', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_subtype', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitTogether',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_type', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitWreathcrown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_wreathcrown', to='ripdapp.Portrait')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province name??')),
            ],
        ),
        migrations.CreateModel(
            name='Reason_dating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_date', models.TextField(blank=True, null=True, verbose_name='Reason dating')),
            ],
        ),
        migrations.CreateModel(
            name='Recarved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recarved portrait')),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Together',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('together', models.CharField(blank=True, max_length=255, null=True, verbose_name='Together with')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Wreathcrown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other wreath or crown')),
            ],
        ),
        migrations.AddField(
            model_name='portraitwreathcrown',
            name='wreathcrown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_wreathcrown', to='ripdapp.Wreathcrown'),
        ),
        migrations.AddField(
            model_name='portraittype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_type', to='ripdapp.Type'),
        ),
        migrations.AddField(
            model_name='portraittogether',
            name='emperor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_together', to='ripdapp.Together'),
        ),
        migrations.AddField(
            model_name='portraittogether',
            name='portrait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_together', to='ripdapp.Portrait'),
        ),
        migrations.AddField(
            model_name='portraitsubtype',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_subtype', to='ripdapp.Subtype'),
        ),
        migrations.AddField(
            model_name='portraitrecarved',
            name='recarved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_recarved', to='ripdapp.Recarved'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='alternative',
            field=models.ManyToManyField(through='ripdapp.PortraitAlternative', to='ripdapp.Alternative'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='attributes',
            field=models.ManyToManyField(through='ripdapp.PortraitAttributes', to='ripdapp.Attributes'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='charact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portrait_characteristics', to='ripdapp.Characteristics'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='contexts',
            field=models.ManyToManyField(through='ripdapp.PortraitContext', to='ripdapp.Context'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='dating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portrait_dating', to='ripdapp.Reason_dating'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portrait_group', to='ripdapp.Group'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portrait_height', to='ripdapp.Height'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='iconcuirass',
            field=models.ManyToManyField(through='ripdapp.PortraitIconcuirass', to='ripdapp.Iconography'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='materials',
            field=models.ManyToManyField(through='ripdapp.PortraitMaterial', to='ripdapp.Material'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='photo',
            field=models.ManyToManyField(through='ripdapp.PortraitPhoto', to='ripdapp.Photo'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='recarved',
            field=models.ManyToManyField(through='ripdapp.PortraitRecarved', to='ripdapp.Recarved'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='subtype',
            field=models.ManyToManyField(through='ripdapp.PortraitSubtype', to='ripdapp.Subtype'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='together',
            field=models.ManyToManyField(through='ripdapp.PortraitTogether', to='ripdapp.Together'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='type',
            field=models.ManyToManyField(through='ripdapp.PortraitType', to='ripdapp.Type'),
        ),
        migrations.AddField(
            model_name='portrait',
            name='wreathcrown',
            field=models.ManyToManyField(through='ripdapp.PortraitWreathcrown', to='ripdapp.Wreathcrown'),
        ),
        migrations.AddField(
            model_name='photo_photographer',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_grapher', to='ripdapp.Photographer'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_2',
            field=models.ManyToManyField(through='ripdapp.PortraitPhoto', to='ripdapp.Photo'),
        ),
        migrations.AddField(
            model_name='locationprovince',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_province', to='ripdapp.Province'),
        ),
    ]
